# Generated by Django 4.1.5 on 2023-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('company_name', models.CharField(max_length=256, null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_phone_number'),
        ),
    ]
